"""Report rendering: Markdown (for git/LMS) and a self-contained, accessible HTML page."""
from __future__ import annotations

from html import escape as e

from ..models import GradeReport

DIM_LABEL = {
    "code_quality": "Code Quality", "architecture": "Architecture", "security": "Security",
    "testing": "Testing", "devops": "DevOps & Docker",
}
SEV_COLOR = {"critical": "#b91c1c", "high": "#c2410c", "medium": "#a16207", "low": "#1d4ed8", "info": "#4b5563"}


def _label(d: str) -> str:
    return DIM_LABEL.get(d, d.replace("_", " ").title())


def _fmt_ms(ms: int) -> str:
    return f"{ms / 1000:.1f}s" if ms >= 1000 else f"{ms}ms"


# ---------------------------------------------------------------------------------------
def render_markdown(r: GradeReport) -> str:
    v = r.verdict
    out = [
        f"# AutoGrader Report — {r.repo_url}",
        f"Commit `{r.commit_sha[:12]}` · {r.created_at} · mode: {'LLM (' + r.agent_model + ')' if r.llm_mode else 'heuristic'}"
        + (" · served from cache" if r.cache_hit else ""),
        "",
        f"## Final score: **{v.final_score}/100 — {v.grade}**  (judge confidence {v.confidence:.0%})",
        "", v.summary, "",
        "| Dimension | Weight | Specialist | Judge (final) | Rationale |",
        "|---|---:|---:|---:|---|",
    ]
    for d in v.dimensions:
        out.append(f"| {_label(d.dimension)} | {d.weight:.0%} | {d.agent_score}/10 | **{d.final_score}/10** | {d.rationale.replace('|', '/')} |")
    out += ["", "## Top priorities"] + [f"{i}. {p}" for i, p in enumerate(v.top_priorities, 1)]
    out += ["", "## Learning path"] + [f"- {p}" for p in v.learning_path]
    if v.calibration_notes:
        out += ["", "## Judge calibration notes"] + [f"- {n}" for n in v.calibration_notes]

    for a in r.agents:
        out += ["", f"## {a.agent} — {a.score}/10",
                f"_mode: {a.mode} · confidence {a.confidence:.0%} · {_fmt_ms(a.latency_ms)}_" + (f" · ⚠ {a.error}" if a.error else ""),
                "", a.summary]
        if a.strengths:
            out += ["", "**Strengths**"] + [f"- {s}" for s in a.strengths]
        if a.findings:
            out += ["", "| Severity | Finding | File | Recommendation |", "|---|---|---|---|"]
            for f in a.findings:
                out.append(f"| {f.severity} | **{f.title}** — {f.detail} | {f.file or ''} | {f.recommendation} |".replace("\n", " "))

    d = r.docker
    out += ["", "## Docker sandbox",
            f"- Dockerfile: {d.dockerfile_source} ({d.dockerfile_path or 'n/a'})"
            + (f"; also linted: {', '.join(d.other_dockerfiles)}" if d.other_dockerfiles else ""),
            f"- Build: {_status(d.build_ok, d.attempted_build)}" + (f" in {d.build_seconds}s" if d.build_seconds else "")
            + (f", image {d.image_size_mb} MB" if d.image_size_mb else ""),
            f"- Smoke run: {_status(d.run_ok, d.attempted_run)}"]
    if d.skipped_reason:
        out.append(f"- Note: {d.skipped_reason}")
    if d.build_log_tail:
        out += ["", "<details><summary>Build log (tail)</summary>", "", "```", d.build_log_tail, "```", "</details>"]

    out += ["", "## Latency & pipeline",
            f"- Wall-clock: **{_fmt_ms(r.total_ms)}**, sum of stage times: {_fmt_ms(r.sequential_ms)} → parallel speed-up **{r.speedup}×**",
            f"- Critical path: {' → '.join(r.critical_path) or 'n/a'}",
            f"- Tokens: in {r.tokens.input}, out {r.tokens.output}, cache-read {r.tokens.cache_read}, cache-write {r.tokens.cache_write}",
            "", "| Stage | Start | End | Duration | Status |", "|---|---:|---:|---:|---|"]
    for t in sorted(r.timings, key=lambda t: t.start_ms):
        out.append(f"| {t.name} | {t.start_ms} | {t.end_ms} | {_fmt_ms(t.duration_ms)} | {t.status} |")
    if r.pipeline_notes:
        out += [""] + [f"- {n}" for n in r.pipeline_notes]
    out += ["", f"_Generated by AutoGrader v{r.autograder_version}_", ""]
    return "\n".join(out)


def _status(ok, attempted) -> str:
    if not attempted:
        return "not attempted"
    return "✅ success" if ok else "❌ failed"


# ---------------------------------------------------------------------------------------
def render_html(r: GradeReport) -> str:
    v = r.verdict
    dims_rows = "".join(
        f"<tr><th scope='row'>{e(_label(d.dimension))}</th><td>{d.weight:.0%}</td><td>{d.agent_score}</td>"
        f"<td><strong>{d.final_score}</strong></td><td><div class='bar' role='img' aria-label='{d.final_score} out of 10'>"
        f"<span style='width:{d.final_score * 10:.0f}%'></span></div></td><td>{e(d.rationale)}</td></tr>"
        for d in v.dimensions)

    agents_html = []
    for a in r.agents:
        findings = "".join(
            f"<tr><td><span class='sev' style='background:{SEV_COLOR[f.severity]}'>{e(f.severity)}</span></td>"
            f"<td><strong>{e(f.title)}</strong><br>{e(f.detail)}</td><td><code>{e(f.file or '')}</code></td>"
            f"<td>{e(f.recommendation)}</td></tr>" for f in a.findings)
        agents_html.append(f"""
<section class="card" aria-labelledby="ag-{e(a.dimension)}">
  <h3 id="ag-{e(a.dimension)}">{e(a.agent)} <span class="pill">{a.score}/10</span></h3>
  <p class="meta">mode: {e(a.mode)} · confidence {a.confidence:.0%} · {_fmt_ms(a.latency_ms)} · tokens in/out {a.tokens.input}/{a.tokens.output}
  {f'· <span class="warn">⚠ {e(a.error)}</span>' if a.error else ''}</p>
  <p>{e(a.summary)}</p>
  {('<h4>Strengths</h4><ul>' + ''.join(f'<li>{e(s)}</li>' for s in a.strengths) + '</ul>') if a.strengths else ''}
  {('<table><caption class="sr">Findings</caption><thead><tr><th>Severity</th><th>Finding</th><th>File</th><th>Recommendation</th></tr></thead><tbody>' + findings + '</tbody></table>') if a.findings else '<p>No findings.</p>'}
</section>""")

    total = max(r.total_ms, 1)
    crit = set(r.critical_path)
    lanes = "".join(
        f"<div class='lane'><span class='lname'>{e(t.name)}</span><div class='track'>"
        f"<div class='seg {'crit' if t.name in crit else ''} {e(t.status)}' style='left:{t.start_ms / total * 100:.2f}%;"
        f"width:{max(t.duration_ms / total * 100, 0.4):.2f}%' title='{e(t.name)}: {t.start_ms}–{t.end_ms} ms'></div></div>"
        f"<span class='ldur'>{_fmt_ms(t.duration_ms)}</span></div>"
        for t in sorted(r.timings, key=lambda t: (t.start_ms, t.name)))

    d = r.docker
    lint = "".join(f"<li><span class='sev' style='background:{SEV_COLOR[f.severity]}'>{e(f.severity)}</span> "
                   f"<strong>{e(f.title)}</strong> — {e(f.recommendation)}</li>" for f in d.lint)
    stats = r.repo_stats
    stack = "".join(f"<li><strong>{e(k)}</strong>: {e(', '.join(vs))}</li>" for k, vs in (stats.get("stack") or {}).items())
    langs = ", ".join(f"{e(k)} ({n})" for k, n in (stats.get("languages") or {}).items())

    return f"""<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>AutoGrader report — {e(r.repo_url)}</title>
<style>
:root{{--fg:#111827;--muted:#4b5563;--bg:#f8fafc;--card:#fff;--acc:#4f46e5;--crit:#dc2626}}
*{{box-sizing:border-box}} body{{font:15px/1.5 system-ui,Segoe UI,Roboto,sans-serif;color:var(--fg);background:var(--bg);margin:0;padding:24px}}
main{{max-width:1100px;margin:auto}} h1{{margin:0 0 4px;font-size:1.5rem}} h2{{margin-top:32px}}
.meta{{color:var(--muted);font-size:.9rem}} .card{{background:var(--card);border:1px solid #e5e7eb;border-radius:12px;padding:16px 20px;margin:14px 0}}
.hero{{display:flex;gap:24px;align-items:center;flex-wrap:wrap}}
.score{{width:130px;height:130px;border-radius:50%;display:grid;place-items:center;font-size:2rem;font-weight:700;color:#fff;background:var(--acc)}}
.score small{{display:block;font-size:.9rem;font-weight:500;text-align:center}}
table{{width:100%;border-collapse:collapse;font-size:.9rem}} th,td{{text-align:left;padding:8px;border-bottom:1px solid #e5e7eb;vertical-align:top}}
.bar{{background:#e5e7eb;border-radius:6px;height:10px;width:120px}} .bar span{{display:block;height:10px;border-radius:6px;background:var(--acc)}}
.pill{{background:#eef2ff;color:#3730a3;border-radius:999px;padding:2px 10px;font-size:.85rem}}
.sev{{color:#fff;border-radius:4px;padding:1px 6px;font-size:.75rem;text-transform:uppercase}} .warn{{color:#b45309}}
.lane{{display:grid;grid-template-columns:170px 1fr 70px;gap:8px;align-items:center;margin:4px 0;font-size:.85rem}}
.track{{position:relative;height:16px;background:#f1f5f9;border-radius:4px}} .seg{{position:absolute;top:0;height:16px;border-radius:4px;background:#94a3b8}}
.seg.crit{{background:var(--crit)}} .seg.failed{{background:repeating-linear-gradient(45deg,#f87171,#f87171 4px,#fecaca 4px,#fecaca 8px)}}
.ldur{{text-align:right;color:var(--muted)}} pre{{background:#0f172a;color:#e2e8f0;padding:12px;border-radius:8px;overflow:auto;max-height:320px;font-size:.8rem}}
.sr{{position:absolute;left:-9999px}} code{{font-size:.85em}}
</style></head><body><main>
<header class="card hero">
  <div class="score" role="img" aria-label="Final score {v.final_score} out of 100, grade {e(v.grade)}">{v.final_score}<small>{e(v.grade)}</small></div>
  <div><h1>AutoGrader report</h1>
  <p><a href="{e(r.repo_url)}">{e(r.repo_url)}</a> @ <code>{e(r.commit_sha[:12])}</code></p>
  <p class="meta">{e(r.created_at)} · {'LLM mode: ' + e(r.agent_model) + ' (agents), ' + e(r.judge_model) + ' (judge)' if r.llm_mode else 'heuristic mode (no LLM key)'}
  {' · served from cache' if r.cache_hit else ''} · judge confidence {v.confidence:.0%}</p></div>
</header>

<section class="card" aria-labelledby="sum"><h2 id="sum">Judge verdict</h2><p>{e(v.summary)}</p>
<table><thead><tr><th>Dimension</th><th>Weight</th><th>Specialist</th><th>Final</th><th>Score</th><th>Judge rationale</th></tr></thead><tbody>{dims_rows}</tbody></table>
<h3>Top priorities</h3><ol>{''.join(f'<li>{e(p)}</li>' for p in v.top_priorities)}</ol>
<h3>Learning path</h3><ul>{''.join(f'<li>{e(p)}</li>' for p in v.learning_path)}</ul>
{('<h3>Calibration notes</h3><ul>' + ''.join(f'<li>{e(n)}</li>' for n in v.calibration_notes) + '</ul>') if v.calibration_notes else ''}
</section>

<h2>Specialist agents</h2>
{''.join(agents_html)}

<section class="card" aria-labelledby="dock"><h2 id="dock">Docker sandbox</h2>
<p>Dockerfile: <strong>{e(d.dockerfile_source)}</strong> {('(<code>' + e(d.dockerfile_path) + '</code>)') if d.dockerfile_path else ''}
{('· also linted: <code>' + e(', '.join(d.other_dockerfiles)) + '</code>') if d.other_dockerfiles else ''}<br>
Build: {_status(d.build_ok, d.attempted_build)}{f' in {d.build_seconds}s' if d.build_seconds else ''}{f', image {d.image_size_mb} MB' if d.image_size_mb else ''}<br>
Smoke run (no network, 512 MB, 1 CPU, no capabilities): {_status(d.run_ok, d.attempted_run)}</p>
{f'<p class="warn">{e(d.skipped_reason)}</p>' if d.skipped_reason else ''}
{('<h3>Static lint</h3><ul>' + lint + '</ul>') if lint else ''}
{('<details><summary>Build log (tail)</summary><pre>' + e(d.build_log_tail) + '</pre></details>') if d.build_log_tail else ''}
{('<details><summary>Run log (tail)</summary><pre>' + e(d.run_log_tail) + '</pre></details>') if d.run_log_tail else ''}
</section>

<section class="card" aria-labelledby="lat"><h2 id="lat">Latency &amp; pipeline</h2>
<p>Wall-clock <strong>{_fmt_ms(r.total_ms)}</strong> vs. {_fmt_ms(r.sequential_ms)} if every stage ran sequentially →
<strong>{r.speedup}× speed-up</strong> from the parallel DAG. Red bars = critical path:
<code>{e(' → '.join(r.critical_path) or 'n/a')}</code></p>
<div role="img" aria-label="Pipeline waterfall chart">{lanes}</div>
<p class="meta">Tokens — input {r.tokens.input}, output {r.tokens.output}, prompt-cache read {r.tokens.cache_read}, cache write {r.tokens.cache_write}</p>
{('<ul>' + ''.join(f'<li>{e(n)}</li>' for n in r.pipeline_notes) + '</ul>') if r.pipeline_notes else ''}
</section>

<section class="card" aria-labelledby="repo"><h2 id="repo">Repository facts</h2>
<p>{stats.get('code_files', 0)} code files, {stats.get('source_lines', 0)} source lines, {stats.get('test_files', 0)} test files
(test/source ratio {stats.get('test_to_source_ratio', 0)}), duplication {stats.get('duplication_ratio', 0):.0%}.</p>
<p>Languages: {langs or 'n/a'}</p><ul>{stack}</ul></section>
<p class="meta">Generated by AutoGrader v{e(r.autograder_version)}</p>
</main></body></html>"""
